#include "ctest.h"
#include "functest.h"
#include <stdio.h>
#include <stdlib.h>

CTEST(Game, BubbleSort)
{
    int i = 0, B[4];
    int A[4];
    A[0] = 1;
    A[1] = 3;
    A[2] = 5;
    A[3] = 7;
    B[0] = 5;
    B[1] = 1;
    B[2] = 7;
    B[3] = 3;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    B[0] = 7;
    B[1] = 5;
    B[2] = 3;
    B[3] = 1;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 7;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    B[0] = 5;
    B[1] = 3;
    B[2] = 1;
    B[3] = 7;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    B[0] = 1;
    B[1] = 7;
    B[2] = 5;
    B[3] = 3;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 7;
    B[3] = 5;
    BubbleSort(B, 4);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    ASSERT_EQUAL(A[3], B[3]);
    i++;
    A[0] = 3;
    A[1] = 4;
    A[2] = 10;
    B[0] = 10;
    B[1] = 3;
    B[2] = 4;
    BubbleSort(B, 3);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    i++;
    B[0] = 10;
    B[1] = 4;
    B[2] = 3;
    BubbleSort(B, 3);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    i++;
    B[0] = 4;
    B[1] = 3;
    B[2] = 10;
    BubbleSort(B, 3);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    i++;
    B[0] = 3;
    B[1] = 4;
    B[2] = 10;
    BubbleSort(B, 3);
    ASSERT_EQUAL(A[0], B[0]);
    ASSERT_EQUAL(A[1], B[1]);
    ASSERT_EQUAL(A[2], B[2]);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, FuncStandart)
{
    int a, x, jk, i = 0;

    jk = 3;
    a = 1;
    x = standart(jk);
    ASSERT_EQUAL(x, a);
    i++;
    jk = 4;
    a = 2;
    x = standart(jk);
    ASSERT_EQUAL(x, a);
    i++;
    jk = 2;
    a = 2;
    x = standart(jk);
    ASSERT_EQUAL(x, a);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, StandartGame)
{
    int i = 0, **A, jk = 3, *B, s;
    int a, x;
    A = (int**)malloc(jk * sizeof(int*));
    B = (int*)malloc(jk * sizeof(int));
    s = 0;
    B[0] = 3;
    B[1] = 5;
    B[2] = 7;
    a = 2;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 1;
    B[2] = 1;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 2;
    B[1] = 5;
    B[2] = 10;
    a = 3;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 4;
    B[2] = 10;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 2;
    B[1] = 4;
    B[2] = 8;
    a = 2;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, PlayerTurn)
{
    int i = 0, m, n, B[4];
    int a, x;

    B[0] = 1;
    B[1] = 4;
    B[2] = 7;
    m = 1;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 2;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 1;
    a = 6;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 6;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 7;
    B[2] = 10;
    m = 1;
    n = 2;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 1;
    n = 3;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 3;
    a = 4;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 2;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 7;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 4;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 2;
    B[1] = 6;
    B[2] = 9;
    m = 1;
    n = 2;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 1;
    a = 5;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 1;
    a = 4;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 1;
    a = 3;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 1;
    a = 2;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 6;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 3;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 7;
    m = 1;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 2;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 3;
    a = 2;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 1;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 4;
    a = 3;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 2;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 7;
    m = 1;
    n = 1;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 2;
    n = 3;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 1;
    a = 4;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 2;
    a = 2;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 3;
    n = 2;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 2;
    a = 5;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 4;
    a = 1;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    m = 4;
    n = 10;
    a = 0;
    x = PlayerTurn(B, m, n);
    ASSERT_EQUAL(x, a);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, Winner)
{
    int i = 0, a, x, B[4], jk;
    jk = 3;
    B[0] = 0;
    B[1] = 0;
    B[2] = 0;
    a = 1;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 0;
    B[2] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 1;
    B[2] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 0;
    B[2] = 1;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 2;
    B[1] = 2;
    B[2] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 2;
    B[2] = 2;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 2;
    B[2] = 3;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    jk = 4;
    B[0] = 0;
    B[1] = 0;
    B[2] = 0;
    B[3] = 0;
    a = 1;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 0;
    B[2] = 0;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 2;
    B[2] = 0;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 0;
    B[2] = 1;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 0;
    B[2] = 0;
    B[3] = 4;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 2;
    B[2] = 0;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 0;
    B[2] = 3;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 0;
    B[2] = 0;
    B[3] = 1;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 1;
    B[2] = 2;
    B[3] = 0;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 1;
    B[2] = 0;
    B[3] = 5;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 1;
    B[2] = 2;
    B[3] = 3;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 0;
    B[2] = 2;
    B[3] = 1;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 1;
    B[2] = 2;
    B[3] = 1;
    a = 2;
    x = winner(B, 1, jk);
    ASSERT_EQUAL(x, a);
    i++;
    a = 2;
    x = winner(B, 0, jk);
    ASSERT_EQUAL(x, a);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, MainGames)
{
    int i = 0, **A, jk = 3, B[4];
    int a, x;
    A = (int**)malloc(jk * sizeof(int*));
    B[0] = 1;
    B[1] = 4;
    B[2] = 7;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 1;
    B[2] = 1;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 0;
    B[2] = 1;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 0;
    B[1] = 1;
    B[2] = 1;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 3;
    B[1] = 7;
    B[2] = 10;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    jk = 4;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 7;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 1;
    B[2] = 1;
    B[3] = 1;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 2;
    B[2] = 3;
    B[3] = 4;
    a = 1;
    x = games(A, B, jk);
    ASSERT_EQUAL(x, a);
    i++;
    printf("\nAsserts passed: %d ", i);
}

CTEST(Game, Marienbad)
{
    int i, **A, jk = 4, *B, s;
    int a, x;
    A = (int**)malloc(jk * sizeof(int*));
    B = (int*)malloc(jk * sizeof(int));
    s = 0;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 7;
    i = 0;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    s = 1;
    a = 5;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 1;
    B[2] = 1;
    B[3] = 1;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 3;
    B[3] = 3;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 5;
    B[3] = 5;
    a = 3;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 3;
    B[2] = 0;
    B[3] = 0;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    B[0] = 1;
    B[1] = 2;
    B[2] = 2;
    B[3] = 2;
    a = 1;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    i++;
    a = 0;
    x = ComputerTurn(A, B, jk, s);
    ASSERT_EQUAL(x, a);
    printf("\nAsserts passed: %d ", i);
}
