#ifndef _SRC_INTERSECT_H
#define _SRC_INTERSECT_H
int SectCC(int x1, int u1, int r1, int x2, int u2, int r2);
int SectPC(
        int x1,
        int u1,
        int r1,
        int px1,
        int py1,
        int px2,
        int py2,
        int px3,
        int py3,
        int px4,
        int py4);
int SectPP(
        int px1,
        int py1,
        int px2,
        int py2,
        int px3,
        int py3,
        int px4,
        int py4,
        int px5,
        int py5,
        int px6,
        int py6,
        int px7,
        int py7,
        int px8,
        int py8);
int SectPT(
        int xt1,
        int yt1,
        int xt2,
        int yt2,
        int xt3,
        int yt3,
        int px4,
        int py4,
        int px5,
        int py5,
        int px6,
        int py6,
        int px7,
        int py7);
int SectTC(
        int x1,
        int u1,
        int r1,
        int xt1,
        int yt1,
        int xt2,
        int yt2,
        int xt3,
        int yt3);
int SectTT(
        int xt1,
        int yt1,
        int xt2,
        int yt2,
        int xt3,
        int yt3,
        int xt4,
        int yt4,
        int xt5,
        int yt5,
        int xt6,
        int yt6);
#endif
